// Code generated by gen-sumdb-recordings.go. DO NOT EDIT.

package gomodzip

import (
	_ "embed"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"slices"
	"testing"
)

var recordedResponseLines = []string{
	"rsc.io/diff v0.0.0-20190621135850-fe3479844c3c h1:/WCDjRGIVDjKlhtSc1PEApp2fR58gfSVK62dr/yQNyQ=",
}

//go:embed testdata/recordings/config1
var config1 []byte

//go:embed testdata/recordings/cache1
var cache1 []byte

//go:embed testdata/recordings/cache2
var cache2 []byte

//go:embed testdata/recordings/cache3
var cache3 []byte

//go:embed testdata/recordings/cache4
var cache4 []byte

//go:embed testdata/recordings/cache5
var cache5 []byte

//go:embed testdata/recordings/cache6
var cache6 []byte

//go:embed testdata/recordings/cache7
var cache7 []byte

//go:embed testdata/recordings/cache8
var cache8 []byte

//go:embed testdata/recordings/response1
var response1 []byte

//go:embed testdata/recordings/response2
var response2 []byte

//go:embed testdata/recordings/response3
var response3 []byte

//go:embed testdata/recordings/response4
var response4 []byte

//go:embed testdata/recordings/response5
var response5 []byte

//go:embed testdata/recordings/response6
var response6 []byte

//go:embed testdata/recordings/response7
var response7 []byte

//go:embed testdata/recordings/response8
var response8 []byte

func copyFile(t *testing.T, fromDir, from, toDir, to string) {
	t.Helper()

	to = filepath.Join(toDir, filepath.FromSlash(to))
	from = filepath.Join(fromDir, filepath.FromSlash(from))

	toDir = filepath.Dir(to)
	err := os.MkdirAll(toDir, 0o777)
	if err != nil {
		t.Fatalf("failed to create %q: %v", toDir, err)
	}

	w, err := os.Create(to)
	if err != nil {
		t.Fatalf("failed to create %q: %v", to, err)
	}

	defer w.Close()

	r, err := os.Open(from)
	if err != nil {
		t.Fatalf("failed to open %q: %v", from, err)
	}

	_, err = io.Copy(w, r)
	if err != nil {
		t.Fatalf("failed to copy %q to %q: %v", from, to, err)
	}

	err = w.Close()
	if err != nil {
		t.Fatalf("failed to close %q: %v", to, err)
	}

	err = r.Close()
	if err != nil {
		t.Fatalf("failed to close %q: %v", from, err)
	}
}

func writeConfigs(t *testing.T, dir string) {
	err := os.MkdirAll(dir, 0o755)
	if err != nil {
		t.Fatalf("failed to create %s: %v", dir, err)
	}

	from := filepath.Join("testdata", "recordings")
	copyFile(t, from, "config1", dir, "sum.golang.org/latest")
}

func writeCache(t *testing.T, dir string) {
	err := os.MkdirAll(dir, 0o755)
	if err != nil {
		t.Fatalf("failed to create %s: %v", dir, err)
	}

	from := filepath.Join("testdata", "recordings")
	copyFile(t, from, "cache1", dir, "sum.golang.org/tile/8/3/000.p/3")
	copyFile(t, from, "cache2", dir, "sum.golang.org/tile/8/2/003.p/104")
	copyFile(t, from, "cache3", dir, "sum.golang.org/tile/8/1/872.p/229")
	copyFile(t, from, "cache4", dir, "sum.golang.org/tile/8/0/x223/461.p/253")
	copyFile(t, from, "cache5", dir, "sum.golang.org/tile/8/2/000")
	copyFile(t, from, "cache6", dir, "sum.golang.org/tile/8/1/001")
	copyFile(t, from, "cache7", dir, "sum.golang.org/tile/8/0/494")
	copyFile(t, from, "cache8", dir, "sum.golang.org/lookup/rsc.io/diff@v0.0.0-20190621135850-fe3479844c3c")
}

func addHandler(mux *http.ServeMux, pattern string, payload []byte, header http.Header) {
	mux.HandleFunc(pattern, func(w http.ResponseWriter, r *http.Request) {
		h := w.Header()
		for key, values := range header {
			h[key] = slices.Clone(values)
		}

		w.Write(payload)
	})
}

func addRecordingHandlers(mux *http.ServeMux) {
	addHandler(mux, "GET /lookup/rsc.io/diff@v0.0.0-20190621135850-fe3479844c3c", response1, http.Header{
		"Content-Type": []string{"text/plain; charset=UTF-8"},
	})
	addHandler(mux, "GET /tile/8/0/494", response2, http.Header{
		"Content-Type": []string{"text/plain; charset=UTF-8"},
	})
	addHandler(mux, "GET /tile/8/1/872.p/229", response3, http.Header{
		"Content-Type": []string{"text/plain; charset=UTF-8"},
	})
	addHandler(mux, "GET /tile/8/0/x223/461.p/253", response4, http.Header{
		"Content-Type": []string{"text/plain; charset=UTF-8"},
	})
	addHandler(mux, "GET /tile/8/3/000.p/3", response5, http.Header{
		"Content-Type": []string{"text/plain; charset=UTF-8"},
	})
	addHandler(mux, "GET /tile/8/2/003.p/104", response6, http.Header{
		"Content-Type": []string{"text/plain; charset=UTF-8"},
	})
	addHandler(mux, "GET /tile/8/1/001", response7, http.Header{
		"Content-Type": []string{"text/plain; charset=UTF-8"},
	})
	addHandler(mux, "GET /tile/8/2/000", response8, http.Header{
		"Content-Type": []string{"text/plain; charset=UTF-8"},
	})
}
